name: Coding Standard

on: [push, pull_request]

jobs:
  text-lint:
    name: 'Markdown lint'
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.16.0'
      - run: npm install
      - run: npm run lint
