name: "Sub-Split Components"

on:
  push:
    branches:
      - master
    tags:
      - "**"

jobs:
  narrowspark-subsplit:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      fail-fast: true
      max-parallel: 20
      matrix:
        operating-system: [ubuntu-latest]
        dependencies: [
          "src/Common:git@github.com:narrowspark/automatic-common.git",
          "src/Prefetcher:git@github.com:narrowspark/automatic-composer-prefetcher.git",
          "src/Security:git@github.com:narrowspark/automatic-security-audit.git"
        ]

    name: "Split ${{ matrix.dependencies }}"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: "git-bash"
        uses: fnkr/github-action-git-bash@v1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ secrets.NARROWSPARK_USERNAME }}

      - name: "Configure Container"
        env:
          NARROWSPARK_EMAIL: ${{ secrets.NARROWSPARK_EMAIL }}
          NARROWSPARK_USERNAME: ${{ secrets.NARROWSPARK_USERNAME }}
        run: |
          echo "::set-env name=SOURCE_NAME::${GITHUB_REF#refs/*/}"
          echo "::set-env name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}"
          echo "::set-env name=SOURCE_TAG::${GITHUB_REF#refs/tags/}"

          EMAIL=${NARROWSPARK_EMAIL:-"d.bannert@anolilab.de"}
          NAME=${NARROWSPARK_USERNAME:-"prisis"}

          git config --global user.email "${EMAIL}"
          git config --global user.name "${NAME}"

      - name: "Install Sub-Split"
        run: |
          wget https://github.com/dflydev/git-subsplit/archive/master.tar.gz && tar -zxvf master.tar.gz && rm -rf master.tar.gz
          cd ./git-subsplit-master
          sudo ./install.sh
          cd ..

      - name: "Setup SSH Keys and known_hosts"
        uses: webfactory/ssh-agent@v0.1.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: "Init Sub-Split"
        run: git subsplit init git@github.com:narrowspark/framework.git

      - name: "Splitting ${{ matrix.dependencies }}"
        run: |
          OPTION="--heads=master --no-tags";

          if [[ ${SOURCE_TAG} != ${GITHUB_REF} ]]; then
            OPTION="--tags=\"${SOURCE_TAG}\"";
          fi;

          git subsplit publish ${{ matrix.dependencies }} --update ${OPTION}
