name: 'Coding Standard'

on: [push, pull_request]

jobs:
  php-cs-fixer:
    name: 'PHPStan'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.2
      - run: |
          composer global require narrowspark/coding-standard:3.1.0 slam/phpstan-extensions:3.6.1
          cd $GITHUB_WORKSPACE
          /home/runner/.composer/vendor/bin/phpstan analyse -c phpstan.neon src --memory-limit=-1
