<?php

declare(strict_types=1);

/**
 * This file is part of Narrowspark Framework.
 *
 * (c) Daniel Bannert <d.bannert@anolilab.de>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace Narrowspark\Automatic\Test\Internal;

final class MirrorSettings
{
    public const MIRROR_LIST = [
        'src/Common/Contract/Exception/Exception.php' => [
            'path' => 'Common',
            'namespace' => 'Automatic\\Common',
        ],
        'src/Common/Contract/Exception/InvalidArgumentException.php' => [
            'path' => 'Common',
            'namespace' => 'Automatic\\Common',
        ],
        'src/Common/Contract/Container.php' => [
            'path' => 'Common',
            'namespace' => 'Automatic\\Common',
        ],
        'src/Common/AbstractContainer.php' => [
            'path' => 'Common',
            'namespace' => 'Automatic\\Common',
        ],
        'src/Common/Contract/Resettable.php' => [
            'path' => 'Common',
            'namespace' => 'Automatic\\Common',
        ],
        'src/Common/Traits/GetGenericPropertyReaderTrait.php' => [
            'path' => 'Common',
            'namespace' => 'Automatic\\Common',
        ],
        'src/Common/Contract/Exception/RuntimeException.php' => [
            'path' => 'Common',
            'namespace' => 'Automatic\\Common',
        ],
        'src/Common/Util.php' => [
            'path' => 'Common',
            'namespace' => 'Automatic\\Common',
        ],
    ];

    public const COMMENT_STRING = <<<'STRING'
        /**
         * This file is automatically generated, dont change this file, otherwise the changes are lost after the next mirror update.
         *
         * @codeCoverageIgnore
         * @internal
         */
        STRING;

    public const OUTPUT_LIST = [
        'Prefetcher' . \DIRECTORY_SEPARATOR => 'Automatic\\Prefetcher\\Common',
    ];
}
